exports.seed = function(knex, Promise) {
    return Promise.all([
        Promise.all([
            knex('players').del()
        ])
        .then(function () {
            knex('teams').del();
        })
        .then(function () {
            knex('teams_totals').del();
        })
        .then(function () {
            knex('games').del();
        })
        .then(function () {
            knex('players_teams').del();
        })
        .then(function () {
            knex('players_totals').del();
        })
        .then(function () {
            knex('players_games').del();
        })
    ])
    //insert seed data to each table
    .then(function () {
        return Promise.all([
            knex('players').insert({name:'Todd Gurley', position: 'RB', age:21}),
            knex('players').insert({name:'Tavon Austin', position: 'WR', age:24}),
            knex('players').insert({name:'Nick Foles', position: 'QB', age:26}),
            knex('players').insert({name:'David Johnson', position: 'RB', age:24}),
            knex('players').insert({name:'Larry Fitzgerald', position: 'WR', age:32}),
            knex('players').insert({name:'Carson Palmer', position: 'QB', age:36})
        ]);
    })
    .then(function () {
        return Promise.all([
            knex('teams').insert({city:'St. Louis', name:'Rams'}),
            knex('teams').insert({city:'Arizona', name:'Cardinals'}),
        ]);
    })
    .then(function () {
        return Promise.all([
            knex('teams_totals').insert({
                team_id: 1,
                season: 2015,
                points: 280,
                total_yards: 4761,
                turnovers: 22,
                completions: 273,
                attempts: 473,
                pass_yards: 2805,
                pass_tds: 11,
                interceptions: 11,
                carries: 429,
                rush_yards: 1956,
                rush_tds: 16
            }),
            knex('teams_totals').insert({
                team_id: 2,
                season: 2015,
                points: 489,
                total_yards: 6533,
                turnovers: 24,
                completions: 353,
                attempts: 562,
                pass_yards: 4616,
                pass_tds: 35,
                interceptions: 13,
                carries: 452,
                rush_yards: 1917,
                rush_tds: 16
            }),
        ]);
    })
    .then(function () {
        return Promise.all([
            knex('games').insert({
                home_team_id: 2,
                away_team_id: 1,
                week: 4,
                winner_id: 1,
                home_points: 24,
                away_points: 22,
                home_total_yards: 328,
                home_pass_yards: 164,
                home_rush_yards: 164,
                away_total_yards: 447,
                away_pass_yards: 335,
                away_rush_yards: 113,
                turnovers_forced: 3,
                turnovers_lost: 0,
            }),
            knex('games').insert({
                home_team_id: 1,
                away_team_id: 2,
                week: 13,
                winner_id: 2,
                home_points: 3,
                away_points: 27,
                home_total_yards: 212,
                home_pass_yards: 146,
                home_rush_yards: 66,
                away_total_yards: 524,
                away_pass_yards: 349,
                away_rush_yards: 175,
                turnovers_forced: 0,
                turnovers_lost: 1,
            }),
        ]);
    })
    .then(function () {
        return Promise.all([
            knex('players_teams').insert({player_id: 1, team_id: 1, season: 2015}),
            knex('players_teams').insert({player_id: 2, team_id: 1, season: 2015}),
            knex('players_teams').insert({player_id: 3, team_id: 1, season: 2015}),
            knex('players_teams').insert({player_id: 4, team_id: 2, season: 2015}),
            knex('players_teams').insert({player_id: 5, team_id: 2, season: 2015}),
            knex('players_teams').insert({player_id: 6, team_id: 2, season: 2015})
        ]);
    })
    .then(function () {
        return Promise.all([
            knex('players_totals').insert({
                players_team_id: 1,
                games_played: 13,
                games_started: 12,
                completions: 0,
                attempts: 0,
                pass_tds: 0,
                interceptions: 0,
                pass_yds: 0,
                carries: 229,
                rush_yds: 1106,
                rush_avg: 4.83,
                rush_tds: 10,
                targets: 26,
                receptions: 21,
                rec_yds: 188,
                rec_tds: 0,
                rec_avg: 8.95
            }),
            knex('players_totals').insert({
                players_team_id: 2,
                games_played: 16,
                games_started: 14,
                completions: 0,
                attempts: 0,
                pass_tds: 0,
                interceptions: 0,
                pass_yds: 0,
                carries: 52,
                rush_yds: 434,
                rush_avg: 8.35,
                rush_tds: 4,
                targets: 87,
                receptions: 52,
                rec_yds: 473,
                rec_tds: 5,
                rec_avg: 9.10
            }),
            knex('players_totals').insert({
                players_team_id: 3,
                games_played: 11,
                games_started: 11,
                completions: 190,
                attempts: 337,
                pass_tds: 7,
                interceptions: 10,
                pass_yds: 2052,
                carries: 17,
                rush_yds: 20,
                rush_avg: 1.18,
                rush_tds: 1,
                targets: 0,
                receptions: 0,
                rec_yds: 0,
                rec_tds: 0,
                rec_avg: 0
            }),
            knex('players_totals').insert({
                players_team_id: 4,
                games_played: 16,
                games_started: 5,
                completions: 0,
                attempts: 0,
                pass_tds: 0,
                interceptions: 0,
                pass_yds: 0,
                carries: 125,
                rush_yds: 581,
                rush_avg: 4.65,
                rush_tds: 8,
                targets: 57,
                receptions: 36,
                rec_yds: 457,
                rec_tds: 4,
                rec_avg: 12.69
            }),
            knex('players_totals').insert({
                players_team_id: 5,
                games_played: 16,
                games_started: 16,
                completions: 0,
                attempts: 0,
                pass_tds: 0,
                interceptions: 0,
                pass_yds: 0,
                carries: 0,
                rush_yds: 0,
                rush_avg: 0,
                rush_tds: 0,
                targets: 145,
                receptions: 109,
                rec_yds: 1215,
                rec_tds: 9,
                rec_avg: 11.15
            }),
            knex('players_totals').insert({
                players_team_id: 6,
                games_played: 16,
                games_started: 16,
                completions: 342,
                attempts: 537,
                pass_tds: 35,
                interceptions: 11,
                pass_yds: 4671,
                carries: 25,
                rush_yds: 24,
                rush_avg: 0.96,
                rush_tds: 1,
                targets: 0,
                receptions: 0,
                rec_yds: 0,
                rec_tds: 0,
                rec_avg: 0
            }),
        ]);
    })
    .then(function () {
        return Promise.all([
            knex('players_games').insert({
                players_teams_id: 1,
                game_id: 1,
                completions: 0,
                attempts: 0,
                pass_tds: 0,
                interceptions: 0,
                pass_yds: 0,
                times_sacked: 0,
                pass_long: 0,
                carries: 19,
                rush_yds: 146,
                rush_tds: 0,
                rush_long: 52,
                targets: 2,
                receptions: 2,
                rec_yds: 15,
                rec_tds: 0,
                rec_long: 8,
                fumbles: 1,
                fumbles_lost: 0
            }),
            knex('players_games').insert({
                players_teams_id: 2,
                game_id: 1,
                completions: 0,
                attempts: 0,
                pass_tds: 0,
                interceptions: 0,
                pass_yds: 0,
                times_sacked: 0,
                pass_long: 0,
                carries: 2,
                rush_yds: 20,
                rush_tds: 0,
                rush_long: 12,
                targets: 7,
                receptions: 6,
                rec_yds: 96,
                rec_tds: 2,
                rec_long: 47,
                fumbles: 0,
                fumbles_lost: 0
            }),
            knex('players_games').insert({
                players_teams_id: 3,
                game_id: 1,
                completions: 16,
                attempts: 24,
                pass_tds: 3,
                interceptions: 0,
                pass_yds: 171,
                times_sacked: 1,
                pass_long: 47,
                carries: 1,
                rush_yds: -1,
                rush_tds: 0,
                rush_long: -1,
                targets: 0,
                receptions: 0,
                rec_yds: 0,
                rec_tds: 0,
                rec_long: 0,
                fumbles: 0,
                fumbles_lost: 0
            }),
            knex('players_games').insert({
                players_teams_id: 4,
                game_id: 1,
                completions: 0,
                attempts: 0,
                pass_tds: 0,
                interceptions: 0,
                pass_yds: 0,
                times_sacked: 0,
                pass_long: 0,
                carries: 3,
                rush_yds: 18,
                rush_tds: 0,
                rush_long: 12,
                targets: 10,
                receptions: 4,
                rec_yds: 63,
                rec_tds: 1,
                rec_long: 23,
                fumbles: 1,
                fumbles_lost: 1
            }),
            knex('players_games').insert({
                players_teams_id: 5,
                game_id: 1,
                completions: 0,
                attempts: 0,
                pass_tds: 0,
                interceptions: 0,
                pass_yds: 0,
                times_sacked: 0,
                pass_long: 0,
                carries: 0,
                rush_yds: 0,
                rush_tds: 0,
                rush_long: 0,
                targets: 9,
                receptions: 7,
                rec_yds: 99,
                rec_tds: 0,
                rec_long: 22,
                fumbles: 1,
                fumbles_lost: 1
            }),
            knex('players_games').insert({
                players_teams_id: 6,
                game_id: 1,
                completions: 29,
                attempts: 46,
                pass_tds: 1,
                interceptions: 1,
                pass_yds: 352,
                times_sacked: 4,
                pass_long: 23,
                carries: 1,
                rush_yds: -1,
                rush_tds: 0,
                rush_long: -1,
                targets: 0,
                receptions: 0,
                rec_yds: 0,
                rec_tds: 0,
                rec_long: 0,
                fumbles: 1,
                fumbles_lost: 0
            }),
            knex('players_games').insert({
                players_teams_id: 1,
                game_id: 2,
                completions: 0,
                attempts: 0,
                pass_tds: 0,
                interceptions: 0,
                pass_yds: 0,
                times_sacked: 0,
                pass_long: 0,
                carries: 9,
                rush_yds: 41,
                rush_tds: 0,
                rush_long: 34,
                targets: 0,
                receptions: 0,
                rec_yds: 0,
                rec_tds: 0,
                rec_long: 0,
                fumbles: 0,
                fumbles_lost: 0
            }),
            knex('players_games').insert({
                players_teams_id: 2,
                game_id: 2,
                completions: 0,
                attempts: 0,
                pass_tds: 0,
                interceptions: 0,
                pass_yds: 0,
                times_sacked: 0,
                pass_long: 0,
                carries: 2,
                rush_yds: 14,
                rush_tds: 0,
                rush_long: 12,
                targets: 3,
                receptions: 1,
                rec_yds: 24,
                rec_tds: 0,
                rec_long: 24,
                fumbles: 0,
                fumbles_lost: 0
            }),
            knex('players_games').insert({
                players_teams_id: 3,
                game_id: 2,
                completions: 15,
                attempts: 35,
                pass_tds: 0,
                interceptions: 1,
                pass_yds: 146,
                times_sacked: 0,
                pass_long: 30,
                carries: 2,
                rush_yds: -2,
                rush_tds: 0,
                rush_long: -1,
                targets: 0,
                receptions: 0,
                rec_yds: 0,
                rec_tds: 0,
                rec_long: 0,
                fumbles: 0,
                fumbles_lost: 0
            }),
            knex('players_games').insert({
                players_teams_id: 4,
                game_id: 2,
                completions: 0,
                attempts: 0,
                pass_tds: 0,
                interceptions: 0,
                pass_yds: 0,
                times_sacked: 0,
                pass_long: 0,
                carries: 22,
                rush_yds: 99,
                rush_tds: 0,
                rush_long: 23,
                targets: 3,
                receptions: 2,
                rec_yds: 21,
                rec_tds: 1,
                rec_long: 11,
                fumbles: 1,
                fumbles_lost: 0
            }),
            knex('players_games').insert({
                players_teams_id: 5,
                game_id: 2,
                completions: 0,
                attempts: 0,
                pass_tds: 0,
                interceptions: 0,
                pass_yds: 0,
                times_sacked: 0,
                pass_long: 0,
                carries: 0,
                rush_yds: 0,
                rush_tds: 0,
                rush_long: 0,
                targets: 11,
                receptions: 8,
                rec_yds: 55,
                rec_tds: 0,
                rec_long: 23,
                fumbles: 0,
                fumbles_lost: 0
            }),
            knex('players_games').insert({
                players_teams_id: 6,
                game_id: 2,
                completions: 26,
                attempts: 40,
                pass_tds: 2,
                interceptions: 0,
                pass_yds: 356,
                times_sacked: 2,
                pass_long: 68,
                carries: 0,
                rush_yds: 0,
                rush_tds: 0,
                rush_long: 0,
                targets: 0,
                receptions: 0,
                rec_yds: 0,
                rec_tds: 0,
                rec_long: 0,
                fumbles: 0,
                fumbles_lost: 0
            }),
        ]);
    });
    // Deletes ALL existing entries
};
